# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-06 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_of_gate', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=materials.models.upload_doc_to_with_name)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='materials.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=materials.models.upload_img_to_with_name)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=materials.models.store_thumnail)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='materials.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=materials.models.upload_vid_to_with_name)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='materials.Material')),
            ],
        ),
    ]
