# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=materials.models.store_thumnail),
        ),
    ]
