# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-28 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_image_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='MaterialDocument',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='MaterialImage',
        ),
        migrations.RenameModel(
            old_name='Link',
            new_name='MaterialLink',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='MaterialVideo',
        ),
    ]
