# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-28 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20190128_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallink',
            name='link',
            field=models.URLField(),
        ),
    ]
