# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=events.models.user_directory_path_img)),
                ('video', models.FileField(blank=True, upload_to=events.models.user_directory_path_vid)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('venue', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
