# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-07 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
