# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_when_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video',
        ),
        migrations.AlterField(
            model_name='event',
            name='when_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
