# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-09 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventphoto',
            name='thumbnail',
        ),
    ]
