# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-09 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventphoto_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.store_thumnail),
        ),
    ]
