# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-09 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190109_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventvideo',
            old_name='photo',
            new_name='video',
        ),
    ]
