# Generated by Django 2.0 on 2019-01-03 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forums.Forum'),
        ),
        migrations.AddField(
            model_name='commentoncomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='forums.Comment'),
        ),
        migrations.AddField(
            model_name='commentoncomment',
            name='reply_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentoncomment',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
