# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 14:19
from __future__ import unicode_literals

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_directory_path, validators=[accounts.validators.validate_image_size, accounts.validators.validate_image_width_and_height]),
        ),
    ]
